### ISSUE TITLE
Provide izettle with more information for receipts

### ISSUE THREAD

**Issue by ViddeM** [hulthe/strecklistan#74]
Currently receipts received from iZettle after purchases from the drawIT shop only contain a cryptic number, it would be nice if we could provide iZettle with the name of the product for this purpose. Not sure if this is possible (@hulthe?)

**Comment by hulthe** [comment]
Issue is with [streckbryggan](https://github.com/chalmersdrawit/streckbryggan), although last time I checked it was blocked by the SDK lacking this feature
